export enum TypeKeys {
    DRAWER_TOGGLE = 'DRAWER_TOGGLE',
    SHOW_PROGRESS = 'SHOW_PROGRESS',
    HIDE_PROGRESS = 'HIDE_PROGRESS',
    REGISTER_USER = 'REGISTER_USER_SUCCESS',
    GET_ALL_USERS = 'GET_ALL_USERS_SUCCESS',
    UPDATE_HOLIDAYS = 'UPDATE_HOLIDAYS',
    GET_USER_DETAILS = 'GET_USER_DETAILS_SUCCESS',
    OTHER_ACTION = 'OTHER_ACTION',
    CREATE_REQUEST = 'CREATE_REQUEST_SUCCESS',
    GET_ALL_REQUESTS = 'GET_ALL_REQUESTS_SUCCESS'
}